name: Cloning Branch on repo
run-name: Github actions test1
on:
  push:
    branches:
      - main
jobs:
  test-create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          name: vetonmilaimi/note-app
          ref: actions-test
      - run: git merge main
